/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#4F46E5',
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4F46E5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        // Theme-aware colors using CSS variables
        theme: {
          primary: 'var(--theme-primary)',
          'primary-hover': 'var(--theme-primary-hover)',
          'primary-muted': 'var(--theme-primary-muted)',
          'primary-subtle': 'var(--theme-primary-subtle)',
          success: 'var(--theme-success)',
          'success-subtle': 'var(--theme-success-subtle)',
          warning: 'var(--theme-warning)',
          'warning-subtle': 'var(--theme-warning-subtle)',
          error: 'var(--theme-error)',
          'error-subtle': 'var(--theme-error-subtle)',
          info: 'var(--theme-info)',
          'info-subtle': 'var(--theme-info-subtle)',
          bg: 'var(--theme-bg)',
          'bg-elevated': 'var(--theme-bg-elevated)',
          'bg-overlay': 'var(--theme-bg-overlay)',
          surface: 'var(--theme-surface)',
          'surface-hover': 'var(--theme-surface-hover)',
          'surface-active': 'var(--theme-surface-active)',
          border: 'var(--theme-border)',
          'border-hover': 'var(--theme-border-hover)',
          'border-active': 'var(--theme-border-active)',
          text: 'var(--theme-text)',
          'text-secondary': 'var(--theme-text-secondary)',
          'text-muted': 'var(--theme-text-muted)',
          'text-disabled': 'var(--theme-text-disabled)',
          'text-inverse': 'var(--theme-text-inverse)',
        },
        // Legacy planner colors (for backwards compatibility)
        planner: {
          primary: 'var(--planner-primary)',
          hover: 'var(--planner-hover)',
          muted: 'var(--planner-muted)',
          bg: 'var(--planner-bg)',
          surface: 'var(--planner-surface)',
          border: 'var(--planner-border)',
        },
      },
      fontFamily: {
        theme: 'var(--theme-font-family)',
      },
      fontSize: {
        'theme-xs': 'var(--theme-font-size-xs)',
        'theme-sm': 'var(--theme-font-size-sm)',
        'theme-base': 'var(--theme-font-size-base)',
        'theme-lg': 'var(--theme-font-size-lg)',
        'theme-xl': 'var(--theme-font-size-xl)',
        'theme-2xl': 'var(--theme-font-size-2xl)',
      },
      spacing: {
        'theme-1': 'var(--theme-spacing-1)',
        'theme-2': 'var(--theme-spacing-2)',
        'theme-3': 'var(--theme-spacing-3)',
        'theme-4': 'var(--theme-spacing-4)',
        'theme-6': 'var(--theme-spacing-6)',
        'theme-8': 'var(--theme-spacing-8)',
      },
      borderRadius: {
        'theme-none': 'var(--theme-radius-none)',
        'theme-sm': 'var(--theme-radius-sm)',
        'theme-md': 'var(--theme-radius-md)',
        'theme-lg': 'var(--theme-radius-lg)',
        'theme-xl': 'var(--theme-radius-xl)',
        'theme-2xl': 'var(--theme-radius-2xl)',
        'theme-full': 'var(--theme-radius-full)',
      },
      boxShadow: {
        'theme-none': 'var(--theme-shadow-none)',
        'theme-sm': 'var(--theme-shadow-sm)',
        'theme-md': 'var(--theme-shadow-md)',
        'theme-lg': 'var(--theme-shadow-lg)',
        'theme-xl': 'var(--theme-shadow-xl)',
        'theme-glow': 'var(--theme-shadow-glow)',
        'theme-glow-strong': 'var(--theme-shadow-glow-strong)',
      },
      transitionDuration: {
        'theme-fast': 'var(--theme-duration-fast)',
        'theme-normal': 'var(--theme-duration-normal)',
        'theme-slow': 'var(--theme-duration-slow)',
      },
      transitionTimingFunction: {
        'theme-default': 'var(--theme-easing-default)',
        'theme-bounce': 'var(--theme-easing-bounce)',
        'theme-smooth': 'var(--theme-easing-smooth)',
      },
    },
  },
  plugins: [],
};
