<template>
  <header class="sticky top-0 z-30 border-b border-line bg-paper">
    <div
      class="mx-auto flex h-16 max-w-site items-center justify-between gap-9 px-5 md:h-[76px] md:px-10"
    >
      <NuxtLink :to="lp('home')" class="flex flex-col items-start gap-[3px]" :aria-label="c.nav.homeAria">
        <span class="font-logo text-[21px] font-medium leading-none tracking-[-0.035em]">plusultra</span>
        <span class="flex items-center gap-[7px]">
          <!-- "Plus ultra" — further beyond. Three dashes, each longer than
               the last, running into the arrowhead. Geometry generated by
               scripts/export-brand.py, which draws the exported logo files
               from the same numbers. -->
          <svg
            class="pu-wipe block h-[8.75px] w-[34px] text-accent"
            viewBox="0 -3.75 34 8.75"
            fill="currentColor"
            aria-hidden="true"
          >
            <rect x="0" y="0" width="4.04" height="1.25" />
            <rect x="6.79" y="0" width="6.46" height="1.25" />
            <rect x="16" y="0" width="10.5" height="1.25" />
            <path
              d="M27.5 -3.12 L34 0.62 L27.5 4.38"
              fill="none"
              stroke="currentColor"
              stroke-width="1.25"
              stroke-linejoin="miter"
            />
          </svg>
          <span class="font-mono text-[9.5px] tracking-[0.24em] text-muted">LABS</span>
        </span>
      </NuxtLink>

      <nav class="hidden items-center gap-8 text-[15.5px] font-semibold md:flex">
        <NuxtLink
          v-for="item in links"
          :key="item.to"
          :to="item.to"
          class="text-muted transition-colors duration-[250ms] hover:text-ink"
          active-class="!text-ink"
        >
          {{ item.label }}
        </NuxtLink>
      </nav>

      <div class="hidden items-center gap-5 self-stretch md:flex">
        <ThemeToggle />
        <LanguageSwitcher />
        <BookCallButton size="sm" arrow />
      </div>

      <button
        class="-mr-3 flex h-12 w-12 items-center justify-center md:hidden"
        :aria-label="c.nav.menuAria"
        :aria-expanded="open"
        @click="open = !open"
      >
        <svg width="24" height="16" viewBox="0 0 24 16" aria-hidden="true" class="text-ink">
          <rect x="0" y="2" width="24" height="2.5" fill="currentColor" />
          <rect :x="open ? 0 : 8" y="11" :width="open ? 24 : 16" height="2.5" fill="currentColor" />
        </svg>
      </button>
    </div>

    <div v-if="open" class="border-t border-line bg-paper px-5 pb-6 md:hidden">
      <div class="flex flex-col">
        <NuxtLink
          v-for="item in links"
          :key="item.to"
          :to="item.to"
          class="flex min-h-[60px] items-center justify-between border-b border-line text-[22px] font-extrabold font-display"
          @click="open = false"
        >
          {{ item.label }}
          <ChevronIcon :size="13" class="text-accent" />
        </NuxtLink>
        <div class="flex items-center justify-between gap-4 pt-5">
          <LanguageSwitcher />
          <ThemeToggle with-label />
        </div>
      </div>
    </div>
  </header>
</template>

<script setup lang="ts">
const open = ref(false);

// Close the mobile menu on any route change, including taps on the logo.
const route = useRoute();
watch(() => route.fullPath, () => (open.value = false));

// And when the booking dialog covers it, so it is not still hanging open
// behind the modal once the visitor closes it.
const { isOpen: bookingOpen } = useBookCall();
watch(bookingOpen, (v) => {
  if (v) open.value = false;
});

const c = useCopy();
const lp = useLocalePath();

const links = computed(() => [
  { to: lp("services"), label: c.value.nav.services },
  { to: lp("work"), label: c.value.nav.work },
  { to: lp("about"), label: c.value.nav.about },
  { to: lp("contact"), label: c.value.nav.contact },
]);
</script>
